### ISSUE TITLE
Domain Name

### ISSUE THREAD

**Issue by derekjwong95** [Project-35/power8ci#6]
Decide on a Domain Name

**Comment by gerrith3** [comment]
I would recommend something like power-ci.[standard osl domain name].  Lance could probably help validate/identify.

**Comment by ramereth** [comment]
We can provide something like power-ci.osuosl.org.

**Comment by gerrith3** [comment]
That is simple and straightforward.  I would suggest to @derekjwong95 that we make it so and can close an issue.  ;)

**Comment by ramereth** [comment]
Just let me know where to point it and when to do it. Or @leel8on can do it too.
