### ISSUE TITLE
Tracing States of Builds

### ISSUE THREAD

**Issue by derekjwong95** [Project-35/power8ci#8]

**Comment by gerrith3** [comment]
@derekjwong95 for everyone else on the list, can you update the description a bit - what states do we want to trace, and when?

**Comment by derekjwong95** [comment]
@gerrith3 actually this might be a bad issue now that I thought about it and it should just be one issue with the "reporting build status to users". Initially, we intended to simply use the Build Monitor Plugin to show the users the status of their build and potentially who might be responsible for "breaking the build". I think that information is enough for the users, unless you think we should have the functionality to trace each state of the build.

**Comment by gerrith3** [comment]
@derekjwong95 I would agree - the build monitor plug in should be good enough.  Are there multiple monitors?  @seth-priya or @ghatwala which monitor do we use today?

**Comment by ghatwala** [comment]
@derekjwong95 @gerrith3 - we don't use any build monitor plug in as such  in our set up .But we use email notification plugin  as pointed out here - https://github.com/Project-35/power8ci/issues/7
This plugin helps in indicating to the user the reason for the job failure by mails.
